<template>
    <div class="child8">
      <br>
      小版本
      <i class="el-icon-caret-bottom"></i><br/><br/>
      <el-table
        :data="tableData0"
        ref="multipleTable"
        @selection-change="handleSelectionChange"
        border
        style="width: 100%">
        <el-table-column
        type="selection"
        width="55">
        </el-table-column>
        <el-table-column
          prop="1"
          label="序号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="2"
          label="编号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="3"
          label="名称"
          width="100">
        </el-table-column>
        <el-table-column
          prop="4"
          label="上下文"
          width="100">
        </el-table-column>
        <el-table-column
          prop="5"
          label="版本"
          width="100">
        </el-table-column>
        <el-table-column
          prop="6"
          label="状态"
          width="100">
        </el-table-column>
        <el-table-column
          prop="7"
          label="位置"
          width="100">
        </el-table-column>
        <el-table-column
          prop="8"
          label="修改者"
          width="100">
        </el-table-column>
        <el-table-column
          prop="9"
          label="修改时间"
          width="100">
        </el-table-column>
        <el-table-column
          prop="10"
          label="备注"
          width="100">
        </el-table-column>
      </el-table>
      <br>
      修订版本
      <i class="el-icon-caret-bottom"></i><br/><br/>
      <el-table
        :data="tableData1"
        ref="multipleTable"
        @selection-change="handleSelectionChange"
        border
        style="width: 100%">
        <el-table-column
        type="selection"
        width="55">
        </el-table-column>
        <el-table-column
          prop="1"
          label="序号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="2"
          label="编号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="3"
          label="名称"
          width="100">
        </el-table-column>
        <el-table-column
          prop="4"
          label="上下文"
          width="100">
        </el-table-column>
        <el-table-column
          prop="5"
          label="版本"
          width="100">
        </el-table-column>
        <el-table-column
          prop="6"
          label="状态"
          width="100">
        </el-table-column>
        <el-table-column
          prop="7"
          label="位置"
          width="100">
        </el-table-column>
        <el-table-column
          prop="8"
          label="修改者"
          width="100">
        </el-table-column>
        <el-table-column
          prop="9"
          label="修改时间"
          width="100">
        </el-table-column>
        <el-table-column
          prop="10"
          label="备注"
          width="100">
        </el-table-column>
      </el-table>
      <br>
      重命名
      <i class="el-icon-caret-bottom"></i><br/><br/>
      <el-table
        :data="tableData0"
        ref="multipleTable"
        @selection-change="handleSelectionChange"
        border
        style="width: 100%">
        <el-table-column
        type="selection"
        width="55">
        </el-table-column>
        <el-table-column
          prop="1"
          label="改前编号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="2"
          label="改后编号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="3"
          label="改前名称"
          width="100">
        </el-table-column>
        <el-table-column
          prop="4"
          label="改后名称"
          width="100">
        </el-table-column>
        <el-table-column
          prop="5"
          label="用户"
          width="100">
        </el-table-column>
        <el-table-column
          prop="6"
          label="修改时间"
          width="100">
        </el-table-column>
      </el-table>
      <br>
      文件下载
      <i class="el-icon-caret-bottom"></i><br/><br/>
      <el-table
        :data="tableData0"
        border
        style="width: 100%">
        <el-table-column
          prop="1"
          label="文件名"
          width="100">
        </el-table-column>
        <el-table-column
          prop="2"
          label="下载次数"
          width="100">
        </el-table-column>
        <el-table-column
          prop="3"
          label="下载用户"
          width="100">
        </el-table-column>
        <el-table-column
          prop="4"
          label="下载时间"
          width="100">
        </el-table-column>
        <el-table-column
          prop="5"
          label="下载路径"
          width="100">
        </el-table-column>
      </el-table>
      <br>
      另存为
      <i class="el-icon-caret-bottom"></i><br/><br/>
      <el-table
        :data="tableData0"
        ref="multipleTable"
        @selection-change="handleSelectionChange"
        border
        style="width: 100%">
        <el-table-column
        type="selection"
        width="55">
        </el-table-column>
        <el-table-column
          prop="1"
          label="编号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="2"
          label="版本"
          width="100">
        </el-table-column>
        <el-table-column
          prop="3"
          label="方向"
          width="100">
        </el-table-column>
        <el-table-column
          prop="4"
          label="编号"
          width="100">
        </el-table-column>
        <el-table-column
          prop="5"
          label="版本"
          width="100">
        </el-table-column>
        <el-table-column
          prop="6"
          label="保存者"
          width="100">
        </el-table-column>
        <el-table-column
          prop="7"
          label="修改时间"
          width="100">
        </el-table-column>
      </el-table>
    </div>
    </template>
    
    <script>
      export default {
        name: 'child8',
        data() {
          return {
          }
        }
      }
    </script>